### ISSUE TITLE
Live Preview not working after following all instructions

### ISSUE THREAD

**Issue by thinkflo** [nogn-hq/craft-gridsome#2]
Hi there, I need some help.  I'm evaluating your plugin and followed all instructions and cannot get live preview to work.  It's worthwhile to note that I have a multi-site setup in Craft with two languages.  As a test, I have hardcoded the template to pull from the "en" site as to prevent issues with pulling the proper entry, since multi sites use the same Entry ID for canonical pages.  

I am using Gridsome 0.7.21 and @bhws/gridsome-source-craft-graphql 0.0.14 with Craft Pro 3.5.12.1 and Gridsome Nogn 0.1.2

Here is my test Blog article template named `craftEntryBlog.vue` which matches your template naming convention.  (The section handle is `blog`)

```
<template>
  <Layout>
    <h1>{{ $page.craft.entry.title }}</h1>
    <div>
      {{this.$context.id}}
      {{JSON.stringify($page.craft)}}
    </div>
  </Layout>
</template>

<page-query>
query CraftEntry ($id: [craft_QueryArgument]) {
  craft {
    entry (site: "en", section: "blog", enabledForSite: true, id: $id) {
      title
    }
  }
}
</page-query>
```

Here is my App.vue

```
<template>  
    <router-view>
      <CraftLivePreview endpoint="http://lvh.me/api" />
    </router-view>
</template>

<static-query>
query {
  metadata {
    siteName
    siteDescription
  }
}
</static-query>

<script>
export default {
  components: {
    CraftLivePreview: () => import ('@bhws/gridsome-source-craft-graphql/CraftLivePreview')
  },
  metaInfo() {
    return {
      title: this.$static.metadata.siteName,
      meta: [
        {
          key: 'description',
          name: 'description',
          content: this.$static.metadata.siteDescription
        }
      ]
    }
  }
}
</script>
```

Here is how I am loading your gridsome source plugin in gridsome.config.js

```
      {
        use: '@bhws/gridsome-source-craft-graphql',
        options: {
          url: process.env.CRAFT_API_URL,
          fieldName: 'craft',
          typeName: 'craft',
          dangerouslyAllowAuthorizationHeaders: true,
          livePreview: process.env.CRAFT_LIVE_PREVIEW || false,
          headers: {
            Authorization: `Bearer ${process.env.CRAFT_API_TOKEN}`,
          }          
        }
      },
```

I have appended `?CraftPreviewSlug={slug}` to the Preview Target of the Blog Section and ensured that full public permissions are set to Craft's GraphQL and tested them using the Explorer, both in Craft and in Gridsome Dev.  I have ensured that I have `CRAFT_LIVE_PREVIEW` in `.env` set to `true`.  The Site's BaseUrl in Craft is set to `http://lvh.me:8080` so that it will use it for the Live Preview iframe and I have Gridsome Development server up and running on that port.  In Gridsome Nogn plugin, I have a site setup at the same URL with the Blog section selected and saved. 

With all that, when I try to change the title when editing a Blog article, the live preview iframe refreshes and even the tokens change when I inspect, but I do not get the live preview updates working.  The titles never change from the initial blog article.  And I have no console errors or any network errors when I inspect, so everything seems to be working but no updates. Help?

**Comment by sanscheese** [comment]
Closing this for the multi-site feature request in #3 :)
