### ISSUE TITLE
Deprecation warning: craft.sections.getAllSections() has been deprecated.

### ISSUE THREAD

**Issue by alexroper** [nogn-hq/craft-gridsome#4]
I'm getting this deprecation warning that appears to be from the Nogn plugin:

> **Message:**craft.sections.getAllSections() has been deprecated. Use craft.app.sections.allSections instead.

> **Origin:** /Users/alexroper/Sites/looma/craft/vendor/nogn/craft-gridsome/src/templates/_sites/edit.html:70

Craft CMS 3.5.17.1
Gridsome Nogn 0.1.2

**Comment by sanscheese** [comment]
Fixed in v0.1.3
