### ISSUE TITLE
Live preview not working

### ISSUE THREAD

**Issue by stuartmitchelhill** [nogn-hq/craft-gridsome#7]
Hi there, I need some help, I followed all instructions and cannot get live preview to work. I have tried in both a local setup and in a staging environment with the front-end hosted on Netlify and the CMS hosted in AWS

I am using Gridsome ^0.7.0 and @nogn/gridsome-source-craft ^0.0.5 with Craft Pro 3.6.12 and nogn/craft-gridsome 0.1.5.

I had live preview working previously with the depreciated @bhws/gridsome-source-craft-graphql gridsome plugin, however after switching to NOGN and following the live preview instructions on Nogn's documentation live preview does not work. Do I need to include the Craft Live preview component (`<CraftLivePreview endpoint="https://example.com/api" />`) and append `?CraftPreviewId={id}`  or is there something else I am missing?

**Comment by sanscheese** [comment]
Live preview *should* just be a matter of setting `livePreview: true` in the config options for gridsome-source-craft. [See step 4 of Gridsome steps](https://nogn.io/gridsome-craft/getting-started/)  (NOGN doesn't need a `CraftLivePreview` component imported)

Are you getting any console errors with live preview?

 (I'm assuming you've successfully been able to `build` the site with craft data and the data shows in gridsome's `___explore` endpoint)

**Comment by stuartmitchelhill** [comment]
Hi @sanscheese thanks for you help, I can confirm I am following step 4 of gridsome steps in the documentation, below is an example of my env var 

```
VUE_APP_CRAFT_API_URL=http://admin.tundra.local/api
VUE_APP_CRAFT_API_TOKEN=XXXXXXXXXXXXXXXXXXXX
VUE_APP_CRAFT_LIVE_PREVIEW=true
VUE_APP_NODE_ENV=development
```

And here is my gridsome.config.js

```
module.exports = {
  siteName: 'Tundra',
  plugins: [
    {
      use: '@nogn/gridsome-source-craft',
      options: {
        url: process.env.VUE_APP_CRAFT_API_URL,
        livePreview: process.env.VUE_APP_CRAFT_LIVE_PREVIEW || false,
        headers: {
          Authorization: `Bearer ${process.env.VUE_APP_CRAFT_API_TOKEN}`
        }
      },
    },
  ],
}
```

And here are some screens of the Nogn settings in Craft as well as my GraphQL schema settings

<img width="1106" alt="Screen Shot 2021-04-27 at 9 14 03 am" src="https://user-images.githubusercontent.com/13814948/116162425-1effff00-a739-11eb-9ad4-34ec02e8d4b6.png">

<img width="1102" alt="Screen Shot 2021-04-27 at 9 14 20 am" src="https://user-images.githubusercontent.com/13814948/116162433-21faef80-a739-11eb-88c1-dace0de959c3.png">

I do get a console error in live preview `"TypeError: Cannot read property 'entry' of undefined"` where entry is a GraphQL var from Craft

And yes running `gridsome develop` works as expected with all my data in the `__explore` endpoint, and `gridsome build` works as expected both locally and on a server

Any ideas what could be causing the console error in live preview? 

Thanks in advance,
Stuart

**Comment by sanscheese** [comment]
Ahh as you're using a token for the graphql endpoint change your env

`VUE_APP_CRAFT_LIVE_PREVIEW=true` to 

`VUE_APP_CRAFT_LIVE_PREVIEW=dangerouslyAllowAuthorizationHeaders`

This is done to highlight the risk as the key will be exposed to the client. So you may want a password protected staging area or at least be comfortable with what is being exposed with that key.

I'll update the docs as that isn't clear. 😀

**Comment by stuartmitchelhill** [comment]
@sanscheese that's working perfectly now, thanks very much for your support I really appreciate it! Love your work!!
