### ISSUE TITLE
Deprication warnings with Craft 3.7

### ISSUE THREAD

**Issue by chadclark** [nogn-hq/craft-gridsome#8]
Upgrading from Craft `3.6.x` to `3.7.5` introduced two new deprecation warnings related to `craft-gridsome`:

Message: `Elements’ getSourceUid() method has been deprecated. Use getCanonical(true)-&gt;uid instead.`
Origin: `/app/vendor/nogn/craft-gridsome/src/CraftGridsome.php:122`

Message: `Elements’ getSourceId() method has been deprecated. Use getCanonicalId() instead.`
Origin: `/app/vendor/nogn/craft-gridsome/src/CraftGridsome.php:140`

**Comment by sanscheese** [comment]
Fixed in v0.1.6
